-- Green Car Tires counter: every table, in one paste. Supabase > SQL Editor > New query > paste all of this > Run.
-- Same as running supabase/migrations/001 to 004 in order. Safe to run again: nothing is dropped or duplicated.
-- Generated by: npm run setup-sql (edit the migrations, not this file).

-- ================================================================ 001_wheelsize_cache.sql
-- Wheel-Size lookups are cached here so each vehicle costs one API hit, ever (until it goes stale).

-- Every make/model sold in the region. Filled once by scripts/seed-models.ts, refreshed yearly.
-- Lets the counter turn "18 outback" into make=subaru, model=outback without spending API hits.
create table if not exists vehicle_models (
  make_slug   text not null,
  make_name   text not null,
  model_slug  text not null,
  model_name  text not null,
  region      text not null default 'cdm',
  -- "cr-v" -> "crv", "f-150" -> "f150", so counter shorthand matches
  model_compact text generated always as (regexp_replace(lower(model_slug), '[^a-z0-9]', '', 'g')) stored,
  make_compact  text generated always as (regexp_replace(lower(make_slug),  '[^a-z0-9]', '', 'g')) stored,
  primary key (make_slug, model_slug, region)
);
create index if not exists vehicle_models_compact_idx on vehicle_models (model_compact text_pattern_ops);

-- Normalized fitment card per vehicle-year (see lib/fitment.ts for the JSON shape).
create table if not exists vehicle_fitment (
  make_slug  text not null,
  model_slug text not null,
  year       int  not null,
  region     text not null default 'cdm',
  data       jsonb not null,            -- Fitment
  raw        jsonb,                     -- untouched Wheel-Size response, for re-normalizing later without new hits
  lug_seat   text check (lug_seat in ('conical','ball','flat')),  -- shop override; wins over the make default
  fetched_at timestamptz not null default now(),
  primary key (make_slug, model_slug, year, region)
);

-- Count API hits per day so the counter can warn before the plan quota runs out.
create table if not exists wheelsize_usage (
  day  date primary key default current_date,
  hits int  not null default 0
);
create or replace function wheelsize_hit() returns int language sql as $$
  insert into wheelsize_usage (day, hits) values (current_date, 1)
  on conflict (day) do update set hits = wheelsize_usage.hits + 1
  returning hits;
$$;

-- Only the server (service role) touches these tables.
alter table vehicle_models  enable row level security;
alter table vehicle_fitment enable row level security;
alter table wheelsize_usage enable row level security;

-- ================================================================ 002_search_log.sql
-- Every counter search is recorded, and every vehicle's factory sizes are stored as rows.

-- 1. Factory and optional sizes per vehicle-year, one row each. Written every time a fitment is saved.
--    Answers "which vehicles run 225/65R17?" for tire-size searches, with no API calls.
create table if not exists fitment_oe_sizes (
  make_slug    text not null,
  model_slug   text not null,
  year         int  not null,
  region       text not null,
  tire_size    text not null,          -- "225/65R17"
  load_index   int,
  speed_rating text,
  rim_diameter numeric,
  rim_width    numeric,
  rim_offset   numeric,
  stock        boolean not null,       -- true = factory size, false = approved option
  trims        text[] not null default '{}',
  primary key (make_slug, model_slug, year, region, tire_size, stock, rim_width, rim_offset),
  foreign key (make_slug, model_slug, year, region)
    references vehicle_fitment (make_slug, model_slug, year, region) on delete cascade
);
create index if not exists fitment_oe_sizes_size_idx on fitment_oe_sizes (tire_size);

-- Rebuild a vehicle's size rows from its fitment JSON. Called by the API after each save,
-- and once below to backfill vehicles already cached.
create or replace function sync_fitment_oe_sizes(p_make text, p_model text, p_year int, p_region text)
returns int language plpgsql as $$
declare n int;
begin
  delete from fitment_oe_sizes where make_slug = p_make and model_slug = p_model and year = p_year and region = p_region;
  insert into fitment_oe_sizes (make_slug, model_slug, year, region, tire_size, load_index, speed_rating,
                                rim_diameter, rim_width, rim_offset, stock, trims)
  select f.make_slug, f.model_slug, f.year, f.region,
         s->>'tire', (s->>'loadIndex')::int, s->>'speedRating',
         (s->>'rimDiameter')::numeric, coalesce((s->>'rimWidth')::numeric, 0), coalesce((s->>'offset')::numeric, 0),
         coalesce((s->>'stock')::boolean, true),
         coalesce(array(select jsonb_array_elements_text(s->'trims')), '{}')
  from vehicle_fitment f, jsonb_array_elements(f.data->'oe') s
  where f.make_slug = p_make and f.model_slug = p_model and f.year = p_year and f.region = p_region
  on conflict do nothing;
  get diagnostics n = row_count;
  return n;
end $$;

select sync_fitment_oe_sizes(make_slug, model_slug, year, region) from vehicle_fitment;

-- 2. One row per settled counter search (not per keystroke).
create table if not exists counter_searches (
  id             bigint generated always as identity primary key,
  searched_at    timestamptz not null default now(),
  kind           text not null check (kind in ('vehicle','size')),
  query          text not null,          -- exactly what was typed: "18 outback", "225 65 17"
  year           int,
  make_slug      text,
  model_slug     text,
  tire_size      text,                   -- the size searched, or the OE size selected for a vehicle
  oe_sizes       text[],                 -- factory sizes shown for a vehicle search
  exact_in_stock int not null default 0, -- tires on hand in the exact size
  new_in_stock   int not null default 0, -- of those, new (not used)
  alt_in_stock   int not null default 0, -- tires on hand in safe alternate sizes
  wheels_in_stock int,                   -- wheel lines that fit (vehicle searches only)
  outcome        text not null check (outcome in ('in_stock','used_only','alternate_only','special_order','no_fitment','no_match')),
  fitment_source text check (fitment_source in ('cache','api','stale','none')),
  station        text,                   -- which counter PC, optional
  staff          text                    -- who was at the counter, optional
);
create index if not exists counter_searches_time_idx on counter_searches (searched_at desc);
create index if not exists counter_searches_size_idx on counter_searches (tire_size, searched_at desc);

-- 3. What customers ask for that you can't sell new from the shelf. Use it to decide what to stock.
create or replace view missed_demand_30d as
select tire_size,
       count(*)                                          as searches,
       count(*) filter (where outcome = 'special_order') as special_orders,
       count(*) filter (where outcome = 'alternate_only') as sold_alternate_maybe,
       count(*) filter (where outcome = 'used_only')     as used_only,
       max(searched_at)                                  as last_asked
from counter_searches
where searched_at > now() - interval '30 days'
  and tire_size is not null
  and outcome in ('special_order','alternate_only','used_only')
group by tire_size
order by searches desc;

-- Most-searched vehicles, for deciding which wheels and winter packages to stock.
create or replace view top_vehicles_30d as
select year, make_slug, model_slug, count(*) as searches,
       count(*) filter (where outcome = 'in_stock') as had_stock
from counter_searches
where kind = 'vehicle' and make_slug is not null and searched_at > now() - interval '30 days'
group by year, make_slug, model_slug
order by searches desc;

alter table fitment_oe_sizes enable row level security;
alter table counter_searches enable row level security;

-- ================================================================ 003_inventory.sql
-- Inventory tables. Filled from the Google Sheets, either by the importer page (paste SQL) or the sync route.
-- Each import replaces all rows from that source in one transaction, so the sheet stays the source of truth.

create table if not exists tires (
  id            bigint generated always as identity primary key,
  tire_size     text not null check (tire_size ~ '^\d{3}/\d{2}R\d{2}$'),   -- "225/65R17"
  section_width int  not null,
  aspect_ratio  int  not null,
  rim_diameter  int  not null,
  is_lt         boolean not null default false,  -- light-truck (LT) construction
  brand         text,
  model         text,
  season        text check (season in ('W','AW','AS','S')),  -- winter, all-weather, all-season, summer
  condition     text not null check (condition in ('new','used')),
  tread_32nds   int  check (tread_32nds between 0 and 32),
  load_index    int  check (load_index between 60 and 160),
  load_index_dual int,                           -- LT dual load, e.g. 120/116 -> 116
  speed_rating  text check (speed_rating ~ '^[A-Z]$'),
  is_xl         boolean not null default false,
  dot_year      int  check (dot_year between 1990 and 2100),
  qty           int  not null default 0 check (qty >= 0),
  price         numeric(10,2),                   -- per tire, before install and tax
  location      text,                            -- "Rack B-04"
  notes         text,
  source        text not null,                   -- which sheet/tab it came from
  source_row    int,                             -- row number in the sheet, to find it again
  raw           jsonb,                           -- the original row, untouched
  imported_at   timestamptz not null default now()
);
create index if not exists tires_size_idx on tires (tire_size) where qty > 0;
create index if not exists tires_rim_idx  on tires (rim_diameter, section_width);

create table if not exists wheels (
  id            bigint generated always as identity primary key,
  wheel_type    text not null check (wheel_type in ('alloy','steel')),
  condition     text not null check (condition in ('new','used')),
  grade         text check (grade in ('A','B','C')),   -- used wheels: A clean, B light wear, C cosmetic damage
  diameter      numeric(4,1) not null check (diameter between 12 and 26),
  width         numeric(4,1) check (width between 3 and 14),
  bolt_pattern  text not null check (bolt_pattern ~ '^\d{1,2}x\d{2,3}(\.\d)?$'),   -- "5x114.3"
  bolt_pattern_alt text check (bolt_pattern_alt ~ '^\d{1,2}x\d{2,3}(\.\d)?$'),    -- dual-drilled
  center_bore   numeric(5,1) check (center_bore between 40 and 180),
  wheel_offset  int  check (wheel_offset between -80 and 80),
  description   text,
  finish        text,
  lug_seat      text check (lug_seat in ('conical','ball','flat')),
  has_tpms      boolean,
  qty           int  not null default 0 check (qty >= 0),
  price         numeric(10,2),                  -- per wheel
  location      text,
  notes         text,
  source        text not null,
  source_row    int,
  raw           jsonb,
  imported_at   timestamptz not null default now()
);
create index if not exists wheels_fit_idx on wheels (bolt_pattern, diameter) where qty > 0;
create index if not exists wheels_fit_alt_idx on wheels (bolt_pattern_alt, diameter) where qty > 0 and bolt_pattern_alt is not null;

-- Shop settings that were in the prototype's browser storage: fees, tax, distributor links.
create table if not exists shop_settings (
  key   text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
insert into shop_settings (key, value) values
  ('fees', '{"mountBalance":20,"disposal":5,"tpmsKit":10,"hubRingsSet":25,"lugSet":45,"tpmsSensor":65,"taxPct":13,"altTolerancePct":3}'),
  ('distributors', '[]')
on conflict (key) do nothing;

alter table tires enable row level security;
alter table wheels enable row level security;
alter table shop_settings enable row level security;

-- ================================================================ 004_inventory_sync.sql
-- Automatic Google Sheets sync (POST /api/sync/sheets). Run after 003_inventory.sql.

-- One row per sync that changed something (or was blocked/failed). Runs where the sheet was unchanged
-- only bump checked_at on the latest row, so a 5-minute schedule doesn't flood the table.
create table if not exists inventory_syncs (
  id           bigint generated always as identity primary key,
  synced_at    timestamptz not null default now(),
  checked_at   timestamptz not null default now(),  -- last time the sheet was read and found the same
  trigger      text not null check (trigger in ('cron','manual')),
  kind         text not null check (kind in ('tires','wheels')),
  tabs         text[] not null,
  status       text not null check (status in ('ok','blocked','error')),
  rows_synced  int,
  qty_on_hand  int,
  rejected     int,
  warnings     int,
  content_hash text,                                -- of the sheet cells; equal hash = nothing to do
  message      text
);
create index if not exists inventory_syncs_kind_idx on inventory_syncs (kind, id desc);

-- Replaces every row of tires or wheels with p_rows (a JSON array of cleaned rows) in one transaction:
-- the counter never sees a half-loaded table. The sheet is the source of truth, so rows from the
-- importer page are replaced too. Returns the number of rows inserted.
create or replace function replace_inventory(p_kind text, p_rows jsonb) returns int language plpgsql as $$
declare n int;
begin
  if jsonb_typeof(p_rows) <> 'array' then raise exception 'p_rows must be a JSON array'; end if;
  if p_kind = 'tires' then
    delete from tires where true;   -- "where true": Supabase's safeupdate refuses a bare delete
    insert into tires (tire_size, section_width, aspect_ratio, rim_diameter, is_lt, brand, model, season, condition, tread_32nds,
                       load_index, load_index_dual, speed_rating, is_xl, dot_year, qty, price, location, notes, source, source_row, raw)
    select tire_size, section_width, aspect_ratio, rim_diameter, coalesce(is_lt, false), brand, model, season, condition, tread_32nds,
           load_index, load_index_dual, speed_rating, coalesce(is_xl, false), dot_year, coalesce(qty, 0), price, location, notes, source, source_row, raw
    from jsonb_populate_recordset(null::tires, p_rows);
  elsif p_kind = 'wheels' then
    delete from wheels where true;
    insert into wheels (wheel_type, condition, grade, diameter, width, bolt_pattern, bolt_pattern_alt, center_bore, wheel_offset,
                        description, finish, lug_seat, has_tpms, qty, price, location, notes, source, source_row, raw)
    select wheel_type, condition, grade, diameter, width, bolt_pattern, bolt_pattern_alt, center_bore, wheel_offset,
           description, finish, lug_seat, has_tpms, coalesce(qty, 0), price, location, notes, source, source_row, raw
    from jsonb_populate_recordset(null::wheels, p_rows);
  else
    raise exception 'p_kind must be tires or wheels, got %', p_kind;
  end if;
  get diagnostics n = row_count;
  return n;
end $$;

alter table inventory_syncs enable row level security;

-- Only the server (service role) may call it. RLS already blocks anon writes; this makes it explicit.
do $$ begin
  revoke execute on function replace_inventory(text, jsonb) from public;
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke execute on function replace_inventory(text, jsonb) from anon, authenticated;
  end if;
end $$;
